name: Npm run check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check:
    uses: soos-io/.github/.github/workflows/npm-check-workflow.yml@main
